application: neillatitude
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
- url: /stylesheets
  static_dir: stylesheets
- url: /glDatePicker
  static_dir: glDatePicker
- url: /images
  static_dir: images
- url: /js
  static_dir: js
- url: /_ah/spi/.*
  script: backend.application
- url: /tasks/.*
  script: mylatitude.tasks.application
  secure: always
- url: /admin/.*
  script: mylatitude.admin.application
  secure: always
- url: /.*
  script: latMain.application
  secure: always 
  
libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6
- name: pycrypto
  version: "2.6"
- name: endpoints
  version: "1.0"

builtins:
- remote_api: on
- deferred: on
